server:
  port: 8080
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8484/auth/realms/rms/protocol/openid-connect/certs
          issuer-uri: http://localhost:8484/auth/realms/rms


  datasource:
    url: jdbc:postgresql://localhost:5433/newdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

logging:
  level:
    web: debug