server:
  port: 8080
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8484/auth/realms/my_realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8484/auth/realms/my_realm


logging:
  level:
    web: debug